const reactNativeConfig = require('@react-native/eslint-config/flat');
const jsdoc = require('eslint-plugin-jsdoc');

/**
 * ESLint 9 flat config.
 *
 * `@react-native/eslint-config@0.86.2` ships a `./flat` export (its peer range is
 * `^8 || ^9`), so ESLint 9 needs **no** compatibility shim — no `FlatCompat`, no
 * `ESLINT_USE_FLAT_CONFIG=false`. Both are commonly recommended online and both are
 * strictly worse here. ESLint **10** is a different matter: it falls outside that
 * peer range, which is why the dependency is pinned to `^9`.
 *
 * The RN config already applies `eslint-config-prettier`, which *disables* rules
 * that would fight the formatter rather than running Prettier as a lint rule — so
 * formatting is Prettier's job alone and never produces lint errors.
 */
module.exports = [
  {
    ignores: [
      'node_modules/**',
      'android/**',
      'ios/**',
      'coverage/**',
      'vendor/**',
      // Generated by react-native-bootsplash; not ours to lint.
      'src/shared/assets/generated/**',
    ],
  },

  ...reactNativeConfig,

  {
    /*
     * Disable the two Flow rules the React Native config enables.
     *
     * ⚠️ This is required for ESLint 9, not a preference. `@react-native/eslint-config`
     * bundles `eslint-plugin-ft-flow@2.0.3`, which calls `context.getAllComments()` —
     * a context method ESLint 9 removed in favour of `sourceCode.getAllComments()`.
     * The plugin throws while the *rule* is being constructed, so ESLint aborts with
     * `TypeError: context.getAllComments is not a function` before linting a single
     * file, and the message names ft-flow rather than the config that enabled it.
     *
     * Turning the rules off stops them being constructed at all. Nothing is lost:
     * both exist purely to stop Flow type annotations tripping `no-undef` and
     * `no-unused-vars`, and this codebase is TypeScript with zero Flow files.
     *
     * Revisit if the RN config upgrades its bundled ft-flow past this bug.
     */
    rules: {
      'ft-flow/define-flow-type': 'off',
      'ft-flow/use-flow-type': 'off',
    },
  },

  {
    files: ['**/*.{ts,tsx}'],
    plugins: { jsdoc },
    rules: {
      // The brief grades code comments explicitly, so a small set of jsdoc rules
      // keeps documentation honest rather than merely present. These are the ones
      // that catch *drift* — comments that were true when written and silently
      // stopped being true — which is the failure mode that matters.
      'jsdoc/check-alignment': 'error',
      'jsdoc/check-param-names': 'error', // a renamed parameter with a stale @param
      'jsdoc/check-tag-names': ['error', { typed: true }],
      'jsdoc/empty-tags': 'error',

      // Nudge, don't block: a warning keeps CI green while still flagging an
      // undocumented export in the editor. Making this an error would mean every
      // one-line helper needs a docblock, which is how comment requirements turn
      // into comment noise.
      'jsdoc/require-jsdoc': [
        'warn',
        {
          publicOnly: true,
          require: {
            FunctionDeclaration: true,
            ClassDeclaration: true,
            MethodDefinition: true,
          },
          contexts: ['TSInterfaceDeclaration', 'TSTypeAliasDeclaration'],
        },
      ],

      // TypeScript already proves types; repeating them in prose is pure drift risk.
      'jsdoc/no-types': 'error',
      'jsdoc/require-param-type': 'off',
      'jsdoc/require-returns-type': 'off',
    },
    settings: {
      jsdoc: { mode: 'typescript' },
    },
  },

  {
    // Diagnostics deliberately log to the console: the smoke summary is a single
    // greppable line the build harness asserts on between native-module installs.
    files: ['src/features/diagnostics/**/*.{ts,tsx}'],
    rules: {
      'no-console': 'off',
    },
  },

  {
    // The Jest setup file runs inside Jest but is not itself a test, so it does
    // not match the RN config's test-file glob and would otherwise be linted
    // without the `jest` global in scope.
    files: ['jest.setup.js'],
    languageOptions: { globals: { jest: 'readonly' } },
  },

  {
    // Build-time Node scripts, not app code — they run in Node, not Hermes.
    files: ['scripts/**/*.js'],
    languageOptions: {
      globals: { Buffer: 'readonly', process: 'readonly', console: 'readonly' },
    },
  },

  {
    // `void somePromise` is the conventional, explicit marker for "this promise is
    // deliberately not awaited". Flagging it pushes toward either an empty
    // `.catch(() => {})` or an unmarked floating promise, both of which say less.
    rules: {
      'no-void': ['error', { allowAsStatement: true }],
    },
  },
];
